sudo: no
language: python
install:
  - pip install tox coveralls
script:
  - tox
env:
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py32-django-18
  - TOXENV=py33-django-18
  - TOXENV=py34-django-18
  - TOXENV=py34-django-19
matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=py35-django-19
after_success: coveralls
